name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
     branches:
      - master

jobs:
  build-and-test:
    name: ${{ matrix.os }}/py${{ matrix.python-version }}/uv
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: "0.6.6"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project and dependencies
        run: uv sync --all-extras --group test

      - name: Run tests
        run: uv run pytest --cov=src tests/

      - name: Generate line coverage
        run: uv run coverage report --show-missing

      - name: Upload coverage to Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true

  coveralls-finish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
